#!/bin/bash

SIMULATOR_ROOT="/simulator/BUILD"
SIMULATOR_SCRIPT_FOLDERPATH="$SIMULATOR_ROOT/scripts"
FAKE_ACSPT_SCRIPT_FILENAME="fake_acspt.sh"


if [ ! -d $SIMULATOR_ROOT ] ; then
	echo "Simulator root folder[$SIMULATOR_ROOT] does NOT exist"
	exit 1
fi

cd $SIMULATOR_SCRIPT_FOLDERPATH
./$FAKE_ACSPT_SCRIPT_FILENAME $1
# $SIMULATOR_ROOT/$FAKE_ACSPT_SCRIPT_FILENAME $1
